trigger:
  branches:
    include:
      - main

variables:
  resourceGroup: 'Hub-And-Spoke-RG'
  location: 'eastus'
  vnetTemplateFile: 'infra/vnet.bicep'

stages:
- stage: Deploy
  displayName: 'Deploy Storage Account'
  jobs:
  - deployment: DeployInfra
    displayName: 'Deploy Infra via Bicep'
    environment: hub-and-spoke-env
    pool:
      vmImage: 'ubuntu-latest'

    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: Bash@3
            displayName: 'Login to Azure using Managed Identity'
            inputs:
              scriptType: ps
              targetType: 'inline'
              script: |
                echo "Logging into Azure using Managed Identity..."
                az login

          - task: Bash@3
            displayName: 'Deploy Three VNets and enable Peering'
            inputs:
              scriptType: ps
              targetType: 'inline'
              script: |
                echo "Creating resource group if not exists..."
                az group create --name $(resourceGroup) --location $(location) \
                --output-none

                echo "Deploying Three VNets and enable Peering..."
                az deployment group create \
                  --resource-group $(resourceGroup) \
                  --template-file $(vnetTemplateFile) \
                  --parameters "@infra/parameters.json"


