trigger:
  branches:
    include:
      - main

variables:
  resourceGroup: 'Demo-RG'
  location: 'eastus'
  storageAccountName: 'demostorage$(Build.BuildId)'
  sku: 'Standard_LRS'
  
stages:
- stage: Deploy
  displayName: 'Deploy Storage Account'
  jobs:
  - deployment: DeployStorage
    displayName: 'Deploy Storage via Bicep'
    environment: hub-and-spoke-env
    pool:
      vmImage: 'ubuntu-latest'

    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: Bash@3
            displayName: 'Login to Azure using Managed Identity'
            inputs:
              targetType: 'inline'
              script: |
                echo "Logging into Azure using Managed Identity..."
                az login

          - task: Bash@3
            displayName: 'Deploy Storage Account'
            inputs:
              targetType: 'inline'
              script: |
                echo "Creating resource group if it doesn't exist..."
                az group create --name $(resourceGroup) --location $(location) --output none

                echo "Deploying Storage Account..."
                az deployment group create \
                  --resource-group $(resourceGroup) \
                  --template-file infra/vnet.bicep \
                  --parameters storageAccountName=$(storageAccountName) location=$(location) sku=$(sku) \
                  --output none
