trigger:
  branches:
    include:
      - main

variables:
  resourceGroup: 'Hub-And-Spoke-RG'
  location: 'westus2'
  adminUsername: 'azureuser'
  adminPassword: 'YourP@ssw0rd123!'  

stages:
- stage: Deploy
  displayName: 'Deploy Hub-Spoke VNets and VMs'
  jobs:
  - deployment: DeployInfra
    displayName: 'Deploy VNets and VMs via Bicep'
    environment: hub-and-spoke-env
    pool:
      vmImage: 'ubuntu-latest'

    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - task: Bash@3
            displayName: 'Login to Azure using Managed Identity'
            inputs:
              targetType: 'inline'
              script: |
                echo "Logging into Azure using Managed Identity..."
                az login

          - task: Bash@3
            displayName: 'Create Resource Group if not exists'
            inputs:
              targetType: 'inline'
              script: |
                az group create --name $(resourceGroup) --location $(location) --output none

          - task: Bash@3
            displayName: 'Deploy Hub-Spoke VNets and VMs'
            inputs:
              targetType: 'inline'
              script: |
                az deployment group create \
                  --resource-group $(resourceGroup) \
                  --template-file infra/main.bicep \
                  --parameters location=$(location) \
                               adminUsername=$(adminUsername) \
                               adminPassword=$(adminPassword) \
                  --output none
